name: wattmgr

services:
  wattmgr:
    restart: always
    image: sovcik/wattmgr:latest
    container_name: wattmgr
    volumes:
      - ${WATTMGR_LOG_FOLDER}:/var/log/wattmgr
      - ${WATTMGR_CONFIG_FOLDER}:/app/cfg
